# Generated by Django 2.2.8 on 2020-02-04 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('label',
                 models.CharField(blank=True, default='', max_length=32)),
                (
                    'text',
                    models.TextField(blank=True, default=None, null=True)),
                ('file', models.FileField(
                    blank=True, default=None, null=True,
                    upload_to='%Y-%m-%d')),
                ('is_public', models.BooleanField(default=False)),
                ('created_user', models.UUIDField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('read_grant',
                 models.ForeignKey(
                     db_constraint=False, default=None,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='read_contents',
                     to='grants.Grant')),
                ('write_grant',
                 models.ForeignKey(
                     db_constraint=False, default=None,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='write_contents',
                     to='grants.Grant')),
            ],
        ),
    ]
