# Generated by Django 2.2.8 on 2020-01-30 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGrant',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('created_user', models.UUIDField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'created_user')},
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('label',
                 models.CharField(blank=True, default='', max_length=32)),
                ('text', models.TextField(
                    blank=True, default=None, null=True)),
                ('file', models.FileField(
                    blank=True,
                    default=None,
                    null=True,
                    upload_to='%Y-%m-%d')),
                ('is_public', models.BooleanField(default=False)),
                ('created_user', models.UUIDField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('read_grant',
                 models.ForeignKey(
                     db_constraint=False,
                     default=None,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='read_content',
                     to='contents.ContentGrant')),
                ('write_grant',
                 models.ForeignKey(
                     db_constraint=False,
                     default=None,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='write_content',
                     to='contents.ContentGrant')),
            ],
        ),
        migrations.CreateModel(
            name='ContentGrantUser',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('user', models.UUIDField()),
                ('grant',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='users',
                     to='contents.ContentGrant')),
            ],
            options={
                'unique_together': {('grant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContentGrantScope',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('grant',
                 models.ForeignKey(
                     db_constraint=False,
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='scopes',
                     to='contents.ContentGrant')),
            ],
            options={
                'unique_together': {('grant', 'scope')},
            },
        ),
    ]
