# Generated by Django 2.2.8 on 2020-02-04 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('name', models.CharField(
                    max_length=64,
                    blank=True,
                    default=''
                )),
                ('created_user', models.UUIDField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'created_user')},
            },
        ),
        migrations.CreateModel(
            name='GrantUser',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('user', models.UUIDField()),
                ('grant', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='users',
                    to='grants.Grant')),
            ],
            options={
                'unique_together': {('grant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GrantScope',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('grant', models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='scopes',
                    to='grants.Grant')),
            ],
            options={
                'unique_together': {('grant', 'scope')},
            },
        ),
    ]
