# Generated by Django 2.2.8 on 2020-02-17 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='parent',
            field=models.ForeignKey(
                db_constraint=False, default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='children',
                to='layouts.Layout'),
        ),
    ]
